// Generated by ReScript, PLEASE EDIT WITH CARE


var textEditor = document.getElementById("textEditor");

var textView = document.getElementById("textView");

var selectSmall = document.getElementById("selectSmall");

var selectRegular = document.getElementById("selectRegular");

var selectLarge = document.getElementById("selectLarge");

function updateTextView($$event) {
  textView.innerText = $$event.target.value;
  
}

function changeToSmall(param) {
  textView.classList.add("text-sm");
  textView.classList.remove("text-2xl", "text-6xl");
  
}

function changeToRegular(param) {
  textView.classList.add("text-2xl");
  textView.classList.remove("text-sm", "text-6xl");
  
}

function changeToLarge(param) {
  textView.classList.add("text-6xl");
  textView.classList.remove("text-sm", "text-2xl");
  
}

textEditor.addEventListener("input", updateTextView);

selectSmall.addEventListener("change", changeToSmall);

selectRegular.addEventListener("change", changeToRegular);

selectLarge.addEventListener("change", changeToLarge);

export {
  textEditor ,
  textView ,
  selectSmall ,
  selectRegular ,
  selectLarge ,
  updateTextView ,
  changeToSmall ,
  changeToRegular ,
  changeToLarge ,
  
}
/* textEditor Not a pure module */
